[package]
name = "serde-test"
version = "0.1.0"
authors = ["omicronns <omicronns@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.88", features = ["derive"] }
serde_json = "1.0.38"
rust_decimal = "0.11.1"
